/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiCoursesInIndiaToBecomeAnAiEngineerRouteImport } from './routes/ai-courses-in-india-to-become-an-ai-engineer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCoursesInIndiaToBecomeAnAiEngineerRoute =
  AiCoursesInIndiaToBecomeAnAiEngineerRouteImport.update({
    id: '/ai-courses-in-india-to-become-an-ai-engineer',
    path: '/ai-courses-in-india-to-become-an-ai-engineer',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-courses-in-india-to-become-an-ai-engineer': typeof AiCoursesInIndiaToBecomeAnAiEngineerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-courses-in-india-to-become-an-ai-engineer': typeof AiCoursesInIndiaToBecomeAnAiEngineerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-courses-in-india-to-become-an-ai-engineer': typeof AiCoursesInIndiaToBecomeAnAiEngineerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-courses-in-india-to-become-an-ai-engineer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-courses-in-india-to-become-an-ai-engineer'
  id: '__root__' | '/' | '/ai-courses-in-india-to-become-an-ai-engineer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCoursesInIndiaToBecomeAnAiEngineerRoute: typeof AiCoursesInIndiaToBecomeAnAiEngineerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-courses-in-india-to-become-an-ai-engineer': {
      id: '/ai-courses-in-india-to-become-an-ai-engineer'
      path: '/ai-courses-in-india-to-become-an-ai-engineer'
      fullPath: '/ai-courses-in-india-to-become-an-ai-engineer'
      preLoaderRoute: typeof AiCoursesInIndiaToBecomeAnAiEngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCoursesInIndiaToBecomeAnAiEngineerRoute:
    AiCoursesInIndiaToBecomeAnAiEngineerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
